name: bedrock
recipe: wordpress
proxy:                
  nginx:
    - bedrock.test
  theme:
    - localhost:3000
config:
  php: '7.4'
  via: nginx
  webroot: web
  database: mariadb
  xdebug: true

# Add the following if you plan to use Sage as a starter theme
services:
  theme:
    type: node
    services:
      ports:
        - 3000:3000
tooling:
  yarn:
    service: theme
